.\" Copyright (c) 2009, Members of the EGEE Collaboration.
.\" PEP-C client CLI: pepcli(1) man page
.\" Valery Tschopp - SWITCH
.\" $Id: pepcli.1,v 1.6 2009/06/03 14:02:18 vtschopp Exp $
.TH pepcli 1 "May 2009" "pepcli 1.1.5" "gLite Authorization Service"
.SH NAME
pepcli \- command line interface to the gLite Authorization PEP-C client library
.SH SYNOPSIS
\fBpepcli\fR \-\-pepd \fIURL\fR \-\-certchain \fIFILE\fR [options...]
.PP
\fBpepcli\fR \-\-pepd \fIURL\fR \-\-subjectid \fIID\fR [options...]
.SH DESCRIPTION
The 
.B pepcli
command is the command line interface to the gLite Authorization PEP-C client library. 
This command allow user to submit a XACML Request to a PEP daemon (PEPd) and to receive the XACML Response back.
The XACML Response decision and the received Obligations are displayed as result.
.SH OPTIONS
.TP
\fB\-p\fR \fIURL\fR, \fB\-\-pepd\fR \fIURL\fR
Specify the 
.B mandatory
PEP daemon (PEPd) endpoint \fIURL\fR.
Add multiple \fB\-\-pepd\fR \fIURL\fR options for failover.
.TP
\fB\-c\fR \fIFILE\fR, \fB\-\-certchain\fR \fIFILE\fR
Set the
.B mandatory, and mutually exclusive with the \-\-subjectid option, 
XACML Subject attribute identifier
.B cert\-chain
with the value read from
.IR FILE .
The 
.I FILE
contains a PEM encoded user certificate (X509) or proxy certificate. 
.TP
\fB\-s\fR \fIID\fR, \fB\-\-subjectid\fR \fIID\fR
Set the
.B mandatory, and mutually exclusive with the \-\-certchain option, 
XACML Subject attribute identifier
.B subject\-id
with the value set as the
.IR ID
argument. The
.I ID
is typically a user certificate subject DN in RFC2253 format.
.TP
\fB\-f\fR \fIFQAN\fR, \fB\-\-fqan\fR \fIFQAN\fR
Set the XACML Subject attribute identifiers
.B voms\-primary\-fqan
and
.B voms\-fqan
with the value(s) set as the
.IR FQAN 
argument.
Add multiple \fB\-\-fqan\fR \fIFQAN\fR options for secondary FQANs. The first \fB\-\-fqan\fR \fIFQAN\fR 
option will always be the \fBvoms-primary-fqan\fR attribute value. All specified \fB\-\-fqan\fR \fIFQAN\fR 
option arguments will be add into the \fBvoms-fqan\fR multi-valued attribute values.
.TP
\fB\-r\fR \fIURI\fR, \fB\-\-resourceid\fR \fIURI\fR
Set the XACML Resource attribute identifier
.B resource\-id
with the value set as the
.IR URI
argument.
.TP
\fB\-a\fR \fIURI\fR, \fB\-\-actionid\fR \fIURI\fR
Set the XACML Action attribute identifier
.B action\-id
with the value set as the
.IR URI
argument.
.TP
\fB\-t\fR \fISEC\fR, \fB\-\-timeout\fR \fISEC\fR
Set the PEPd connection timeout to 
.I SEC
second. The default timeout is 10 seconds.
.TP
.BR \-v , " \-\-verbose"
Display verbose information.
.TP
.BR \-x , " \-\-requestcontext"
Display the effective XACML Request context, as processed by the PEP daemon.
Use this option with the \fB\-\-verbose\fR option.
.TP
.BR \-q , " \-\-quiet"
Turn off command output, only the exit status is returned.
.TP
.BR \-d , " \-\-debug"
Display debug information.
.TP
.BR \-h , " \-\-help"
Display a short help text.
.SH OPTIONS NOTES
Using the \fBpepcli\fR command with the \fB\-\-certchain\fR \fIPROXY_FILE\fR and the \fB\-\-fqan\fR \fIFQAN\fR options can give indeterminate
results if the argument \fIPROXY_FILE\fR is a proxy certificate with VOMS AC. 
The PEP daemon X.509 PIP will populate the incoming XACML Request with the proxy certificate VOMS AC into XACML Subject \fBvoms-primary-fqan\fR
and \fBvoms-fqan\fR attributes, therefore, these attributes will be duplicated, resulting in possible inconsistency.
.SH EXIT STATUS
The \fBpepcli\fR command returns a \fB0\fR exit status if it succeeds to submit the XACML Request to a PEP daemon (PEPd) and receives a valid
XACML Response. The XACML Response decision (Permit, Deny, Not Applicable, Indeterminate) does not influence the exit status.
Non zero is returned in case of failure.
.TP
.BR 0
Success.
.TP
.BR 1
Memory allocation error.
.TP
.BR 2
Invalid command option.
.TP
.BR 3
The \fB\-\-certchain\fR argument \fIFILE\fR file does not exist or does not contain a PEM encoded certificate (missing certificate block).
.TP
.BR 4
XACML object creation error.
.TP
.BR 5
Other PEP-C client library error, see output for more information.
.SH AUTHORS
The PEP-C client library and the 
.B pepcli
command are written by Valery Tschopp - SWITCH
.SH COPYRIGHT
Copyright \(co 2009, EGEE
.SH SEE ALSO
.TP 
.I The gLite Authorization Service
https://twiki.cern.ch/twiki/bin/view/EGEE/AuthorizationFramework
.TP
.I Authorization Service: Policy Enforcement Point (PEP)
https://twiki.cern.ch/twiki/bin/view/EGEE/AuthZPEP
